### ISSUE TITLE
Transparent background when only one slide is used

### ISSUE THREAD

**Issue by makcakaya** [TangoAgency/material-intro-screen#133]
I am using v0.0.5 of the library. After showing a splash screen, I jump to the intro and show a few slides. If I show a single slide, the background color is transparent. Is this a bug or a feature? 

How to revert and make it show the background that I set in the code?

See the attached video [here](https://drive.google.com/open?id=1wyZkfcxJVl0_-fMU8UF1GMQRoN84DjpX).

Activity: 

```
package com.markarar.markarar.activities;

import android.os.Bundle;
import android.support.annotation.Nullable;

import com.markarar.markarar.R;

import agency.tango.materialintroscreen.MaterialIntroActivity;
import agency.tango.materialintroscreen.SlideFragmentBuilder;

public class IntroActivity extends MaterialIntroActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // First slide
        addSlide(new SlideFragmentBuilder()
                .backgroundColor(R.color.colorSecondary)
                .buttonsColor(R.color.colorAccent)
                .image(R.drawable.logo_256px_transparent)
                .title(getString(R.string.intro_welcome_title))
                .description(getString(R.string.intro_welcome_description))
                .build());

        // Second slide
/*        addSlide(new SlideFragmentBuilder()
                .backgroundColor(R.color.colorSecondary)
                .buttonsColor(R.color.colorAccent)
                .image(R.drawable.logo_256px_transparent)
                .title(getString(R.string.intro_welcome_title))
                .description(getString(R.string.intro_welcome_description))
                .build());*/
    }
}
```

Manifest:

```
  <activity
            android:name=".activities.IntroActivity"
            android:theme="@style/Theme.Intro" />

```

**Comment by bezmian** [comment]
Hi! Thank you for video. It is a bug, but it is fixed in 0.0.6 version which we will release as soon as possible.

**Comment by makcakaya** [comment]
Thanks for the lightning speed answer. Waiting for the new release.

**Comment by iksena** [comment]
I'm still getting this issue, is there an alternative to solve this? instead of waiting for new release? thanks
